name = "ahos"
compatibility_date = "2026-03-01"
pages_build_output_dir = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "ahos-db"
database_id = "placeholder-set-after-db-creation"
